config/routes.rb
Rails.application.routes.draw do
  resources :users do
	  member do
	    post 'add_friend'
	  end
	end
  root 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user, counter_cache: :friends_count
	belongs_to :friend, class_name: "User"

	after_create :create_inverse, unless: :has_inverse?
	after_destroy :delete_inverse

	private

		def create_inverse
	    Friendship.create(inverse_data)
	  end

	  def has_inverse?
	    Friendship.exists?(inverse_data)
	  end

	  def inverse_data
	    {friend_id: user_id, user_id: friend_id}
	  end

	  def delete_inverse
	  	friendship = Friendship.where(friend_id: user_id, user_id: friend_id).first
  		friendship.destroy if friendship
	  end
end

app/models/heading.rb
class Heading < ApplicationRecord
  belongs_to :website
  delegate :user, to: :website

  scope :by_title, -> (title) { where('lower(title) LIKE ?', "%#{title}%") }

  def self.get_user_ids(title)
  	self.by_title(title).map(&:user).map(&:id).uniq
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_one :website
	accepts_nested_attributes_for :website

	has_many :headings, through: :website
	has_many :friendships
	has_many :friends, through: :friendships

	validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/website.rb
class Website < ApplicationRecord
  belongs_to :user
  has_many :headings

  validates :url, presence: true

  after_validation :shorten_url 

  after_save :fetch_and_create_headings , if: lambda { |u| u['url'][0] != u['url'][1] }

  private

  	def shorten_url
  		short_url = ShortURL.shorten(self.url)
			self.short_url = short_url
  	end

  	# delete all existing headings and fetch new headings only if url changed
  	def fetch_and_create_headings
  		self.headings.destroy_all

  		scrapper = Scrapper.new(self.url)
  		new_headings = scrapper.scrape

  		if new_headings.length
	  		data = []
	  		new_headings.each do |heading|
	  			data << {title: heading, website_id: self.id, created_at: Time.now, updated_at: Time.now}
	  		end
	  		Heading.upsert_all(data)
	  	end
  		
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :update, :edit, :add_friend]   

  def index
  	@users = User.all.includes(:website)
  end

  def show
  	excluded_ids = @user.friend_ids << @user.id
  	@users = User.where.not(id: excluded_ids)
  	@search_results = get_search_result
  end

  def new
  	@user = User.new
  	@user.build_website
  end

  def create
  	@user = User.new user_params
  	if @user.save
  		redirect_to users_path
  	else
  		render 'new'
  	end
  end

  def update
  	if @user.update user_params
  		redirect_to users_path
  	else
  		render 'edit'
  	end
  end

  def edit
  end

  def add_friend
  	friend = User.find params[:friend_id]
  	@user.friends << friend
  	redirect_to @user
  end

  private

  	def find_user
  		@user = User.find params[:id]
  	end

	  def user_params
	    params.require(:user).permit(:name, website_attributes: [:id, :url])
	  end

	  def get_search_result
	  	seach_results = []
	  	if params[:search_topic]
	  		targeted_user_ids = Heading.get_user_ids(params[:search_topic])
	  		targeted_user_ids.each do |targeted_id|
	  			if targeted_id != @user.id
		  			search = Search.new @user.id, targeted_id
		  			result = search.find 
		  			seach_results << result if result
		  		else
		  			seach_results << @user.name
		  		end
	  		end
	  	end
	  	seach_results
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-6">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>
  <%= form.fields_for :website do |website_form| %>
    <div class="form-row">
      <div class="form-group col-6">
        <%= website_form.label :url %>
        <%= website_form.text_field :url, class: "form-control" %>
      </div>
    </div>
  <% end %>
  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class='col-12'>
  <h2>Edit User</h2>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class='col-12'>
  <h1>Listing Users</h1>
  <%= link_to "Add new user", new_user_path %>
</div>
<table class="table table-striped ">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Url</th>
      <th scope="col">Friends Count</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
 <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.name %></td>
        <td><%= user.website.url %></td>
        <td><%= user.friends_count %></td>
        <td><%= link_to 'View', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class='col-12'>
  <h2>Add new User</h2>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class='col-12'>
  <div class='row'>
    <div class="col-6">
      <%= form_tag(user_path(@user), :method => "get", id: "search-form") do %>
        <div class="form-row">
          <div class="form-group col-6">
            <h3>Search</h3>
            <%= text_field_tag :search_topic, params[:search_topic], class: "form-control" %>
          </div>
        </div>
        <%= submit_tag "Search", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
    <div class='col-6'>
      <h3>Search Results</h3>
      <% if !@search_results.blank? %>
        <ul>
          <% @search_results.each do |result| %>
            <li><%= result %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <hr/>
  
  <div class="row">
    <div class="col-6">
      <p>Name: <%= @user.name %></p>
      <p>Url: <%= @user.website.url %></p>
      <p>Short Url: <%= @user.website.short_url %></p>
      <p>Number of Friends: <%= @user.friends_count %></p>
    </div>
    <div class="col-6">
      <h3>Headings</h3>
      <ul>
        <% @user.headings.each do |heading| %>
          <li><%= heading.title %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <hr/>
  
  <div class="row">
    <div class="col-6">
      <h3>Friends</h3>
      <ul>
        <% @user.friends.each do |friend| %>
          <li><%= link_to friend.name, user_path(friend) %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-6">
      <h3>Add Friends</h3>
      <ul>
        <% @users.each do |user| %>
          <li><%= link_to user.name, add_friend_user_path(@user, friend_id: user.id), method: :post %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
</div>